# Although this is a C++ project, we use different PHP versions
language: php

# we need bionic
dist: trusty
sudo: required
group: edge

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly 


# setting the env is the easiest, because it will mix with all the separate php versions (travis does this)
env:
  - COMPILER_PKG=g++-4.8 COMPILER=g++-4.8
  - COMPILER_PKG=g++-4.9 COMPILER=g++-4.9
  - COMPILER_PKG=g++-5 COMPILER=g++-5
  - COMPILER_PKG=g++-6 COMPILER=g++-6
  - COMPILER_PKG=g++-7 COMPILER=g++-7
  - COMPILER_PKG=g++-8 COMPILER=g++-8
  - COMPILER_PKG=clang++-4 COMPILER=clang++-4.0
  - COMPILER_PKG=clang++-5 COMPILER=clang++-5.0
  - COMPILER_PKG=clang++-6 COMPILER=clang++-6.0

matrix:
  allow_failures:
    - php: nightly

before_install:
  # install access to all gcc compilers
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # and all relevant clang compilers
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main"

  # update package index and install correct compiler
  - sudo apt-get -y update
  - sudo apt-get -y --allow-unauthenticated --no-install-recommends install ${COMPILER_PKG}

script:
  # simply make the project with the set compiler
  - make -j4 COMPILER=$COMPILER && sudo make install
