file(GLOB PHPCPP_COMMON_SOURCES CONFIGURE_DEPENDS
      ${CMAKE_CURRENT_SOURCE_DIR}/common/modifiers.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/common/streambuf.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/streambuf.cpp
   )

file(GLOB PHPCPP_COMMON_HEADERS CONFIGURE_DEPENDS
      ${CMAKE_CURRENT_SOURCE_DIR}/common/extensionbase.h
      ${CMAKE_CURRENT_SOURCE_DIR}/common/includes.h
      ${CMAKE_CURRENT_SOURCE_DIR}/common/streambuf.h
   )

file(GLOB PHPCPP_ZEND_SOURCES CONFIGURE_DEPENDS
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/base.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/callable.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/classbase.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/classimpl.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/constant.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/constantfuncs.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/error.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/eval.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/exception.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/exception_handler.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/exists.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/extension.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/extensionimpl.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/file.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/function.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/functor.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/global.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/globals.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/hashmember.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/ini.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/inivalue.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/interface.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/iteratorimpl.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/members.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/modifiers.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/module.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/namespace.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/object.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/sapi.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/script.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/stream.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/streams.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/super.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/throwable.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/value.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/valueiterator.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/zendcallable.cpp
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/zval.cpp
   )


file(GLOB PHPCPP_ZEND_HEADERS CONFIGURE_DEPENDS
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/arithmetic.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/boolmember.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/callable.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/classimpl.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/classtype.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/compileroptions.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/constantimpl.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/delayedfree.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/executestate.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/extensionimpl.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/extensionpath.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/floatmember.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/functor.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/hashiterator.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/includes.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/init.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/invaliditerator.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/iteratorimpl.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/lowercase.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/member.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/method.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/module.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/nativefunction.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/notimplemented.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/nullmember.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/numericmember.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/objectimpl.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/opcodes.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/parametersimpl.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/property.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/rethrowable.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/state.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/string.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/stringmember.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/symbol.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/traverseiterator.h
      ${CMAKE_CURRENT_SOURCE_DIR}/zend/valueiteratorimpl.h
   )

file(GLOB PHPCPP_HEADERS_FILES CONFIGURE_DEPENDS
      ${CMAKE_CURRENT_SOURCE_DIR}/include/argument.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/array.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/arrayaccess.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/base.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/byref.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/byval.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/call.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/class.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/classbase.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/classtype.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/constant.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/countable.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/deprecated.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/error.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/exception.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/extension.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/file.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/function.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/global.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/globals.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/hashmember.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/hashparent.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/ini.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/inivalue.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/interface.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/iterator.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/message.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/modifiers.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/namespace.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/noexcept.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/object.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/parameters.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/platform.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/script.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/serializable.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/stream.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/streams.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/super.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/thread_local.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/throwable.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/traversable.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/type.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/value.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/valueiterator.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/version.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/visibility.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/zendcallable.h
      ${CMAKE_CURRENT_SOURCE_DIR}/include/zval.h
      ${CMAKE_CURRENT_SOURCE_DIR}/phpcpp.h
   )
