name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]
        php: [ 7.2, 7.3, 7.4 ]
        compiler: [ g++-8, g++-9, g++-10, clang-9, clang-10 ]
        exclude:
          - os: ubuntu-16.04
            compiler: g++-10
          - os: ubuntu-16.04
            compiler: clang-10
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - name: Setup Compilers
      run: sudo apt install $COMPILER
      env:
        COMPILER: ${{ matrix.compiler }}
    - name: make
      run: make COMPILER=$COMPILER
      env:
        COMPILER: ${{ matrix.compiler }}
    - name: make install
      run: sudo make install
