name: PHP-CPP
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: [
            '7.0',
            '7.1',
            '7.2',
            '7.3',
            '7.4',
            '8.0',
            '8.1',
            '8.2',
        ]
        compiler: [
            'g++-7',
            'g++-8',
            'g++-9',
            'g++-10',
            'g++-11',
            'clang++-9',
            'clang++-10',
            'clang++-11',
            'clang++-12',
            'clang++-13',
            'clang++-14',
            'clang++-15'
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install access to all gcc compilers
        run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - name: Install access to all relevant clang compilers
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-9 main"
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main"
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main"
      - name: Update package index
        run: sudo apt-get -y update
      - name: Install correct compiler
        run: sudo apt-get -y --allow-unauthenticated --no-install-recommends install ${{ matrix.compiler }}
      - name: Compile and install extension
        run: |
          make -j4 COMPILER=${{ matrix.compiler }}
          sudo make install

